"""Initial migration with updated schema

Revision ID: 55f26e395a5f
Revises: da62520111c4
Create Date: 2025-09-07 13:42:28.097734

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '55f26e395a5f'
down_revision: Union[str, None] = 'da62520111c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
