"""remove_has_paid_from_users_table

Revision ID: 5547b3ec7643
Revises: 45217021b261
Create Date: 2025-09-08 21:33:12.519392

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5547b3ec7643'
down_revision: Union[str, None] = '45217021b261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'refunded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # Remove has_paid column from users table
    op.drop_column('users', 'has_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'refunded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # Add has_paid column back to users table
    op.add_column(
        'users', 
        sa.Column('has_paid', sa.BOOLEAN(), nullable=False, server_default='false')
    )
    # ### end Alembic commands ###
