"""Remove unnecessary chat and message columns

Revision ID: 7ba44fb7730f
Revises: 55f26e395a5f
Create Date: 2025-09-07 14:22:52.805766

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ba44fb7730f'
down_revision: Union[str, None] = '55f26e395a5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns as nullable first
    op.add_column(
        'chats', 
        sa.Column('is_archived_by_initiator', sa.Boolean(), nullable=True)
    )
    op.add_column(
        'chats', 
        sa.Column('is_archived_by_participant', sa.Boolean(), nullable=True)
    )
    
    # Set default values for existing rows
    op.execute(
        "UPDATE chats SET is_archived_by_initiator = false "
        "WHERE is_archived_by_initiator IS NULL"
    )
    op.execute(
        "UPDATE chats SET is_archived_by_participant = false "
        "WHERE is_archived_by_participant IS NULL"
    )
    
    # Now make the columns NOT NULL
    op.alter_column('chats', 'is_archived_by_initiator', nullable=False)
    op.alter_column('chats', 'is_archived_by_participant', nullable=False)
    
    # Drop old columns
    op.drop_column('chats', 'status')
    op.drop_column('chats', 'is_archived')
    op.drop_column('chats', 'is_deleted')
    op.drop_column('chats', 'title')
    op.drop_column('messages', 'edited_at')
    op.drop_column('messages', 'is_flagged')
    op.drop_column('messages', 'flag_reason')
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'is_deleted')
    op.drop_column('messages', 'original_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'messages', 
        sa.Column('original_content', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'messages', 
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'messages', 
        sa.Column(
            'deleted_at', 
            postgresql.TIMESTAMP(), 
            autoincrement=False, 
            nullable=True
        )
    )
    op.add_column(
        'messages', 
        sa.Column('is_edited', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'messages', 
        sa.Column('flag_reason', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'messages', 
        sa.Column('is_flagged', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'messages', 
        sa.Column(
            'edited_at', 
            postgresql.TIMESTAMP(), 
            autoincrement=False, 
            nullable=True
        )
    )
    op.add_column(
        'chats', 
        sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        'chats', 
        sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'chats', 
        sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.add_column(
        'chats', 
        sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_column('chats', 'is_archived_by_participant')
    op.drop_column('chats', 'is_archived_by_initiator')
    # ### end Alembic commands ###
