"""initial database schema

Revision ID: da62520111c4
Revises: 
Create Date: 2025-08-25 13:11:57.696728

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'da62520111c4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
